name: Stage the app

on: 
  pull_request:
    types: [labeled]

env:
  DOCKER_IMAGE_NAME: vijayjethani-azure-ttt
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  AZURE_WEBAPP_NAME: vijayjethani-ttt-app

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'stage')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and webpack build
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@main
        with:
          name: webpack artifacts
          path: public/
          
  build-dockerimage:
    name: build docker image and store in github packages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Download build artifact
        uses: actions/download-artifact@main
        with:
          name: webpack artifacts
          path: public/
          
      - name: Create Image and store in Packages
        uses: mattdavis0351/actions/docker-gpr@1.3.0
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          image-name: ${{env.DOCKER_IMAGE_NAME}}
      
  deploy-azure:
    name: Deploy app container to Azure
    runs-on: ubuntu-latest
    needs: build-dockerimage
    steps:
      - name: login to azure
        uses: azure/login@v1
        with:
         creds: ${{secrets.ACTIONSDEPLOY}}
         
      - name: github registry login
        uses: azure/docker-login@v1
        with:
          login-server: ${{env.IMAGE_REGISTRY_URL}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          
      - name: Deploy Azure Webapp container
        uses: azure/webapps-deploy@v2
        with:
          app-name:  ${{env.AZURE_WEBAPP_NAME}}
          images: ${{env.IMAGE_REGISTRY_URL}}/${{github.reposistory}}/${{env.DOCKER_IMAGE_NAME}}:${{github.sha}}
      
      - name: Azure logout
        run: |
          az logout
