name: Production deployment

on: 
  push:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP: vijaycd-with-actions
  AZURE_APP_PLAN: vijayjethani-ttt-deployment
  AZURE_LOCATION: '"East US"'
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: vijayjethani-ttt-app
  #################################################
